const { join } = require('path');
const harnessUiTailwindConfig = require('@harnessio/ui/tailwind.config');

/** @type {import('tailwindcss').Config} */
module.exports = {
  presets: [harnessUiTailwindConfig],
  content: [join(__dirname, 'webview/**/*.{ts,tsx,html}')],
  theme: {
    extend: {
      fontFamily: {
        sans: ['"IBM Plex Sans"', 'system-ui', 'sans-serif'],
        mono: ['"IBM Plex Mono"', 'ui-monospace', 'SFMono-Regular', 'monospace'],
      },
      colors: {
        vb: {
          ok: 'var(--vb-ok)',
          err: 'var(--vb-err)',
          warn: 'var(--vb-warn)',
          info: 'var(--vb-info)',
          vibe: 'var(--vb-vibe)',
          idle: 'var(--vb-idle)',
          fg: 'var(--vb-fg)',
          'fg-2': 'var(--vb-fg-2)',
          'fg-3': 'var(--vb-fg-3)',
          'fg-4': 'var(--vb-fg-4)',
          'fg-5': 'var(--vb-fg-5)',
          muted: 'var(--vb-muted)',
          dim: 'var(--vb-dim)',
          panel: 'var(--vb-panel)',
          topbar: 'var(--vb-topbar)',
          footer: 'var(--vb-footer)',
          'code-bg': 'var(--vb-code-bg)',
          rule: 'var(--vb-rule)',
          'rule-soft': 'var(--vb-rule-soft)',
          border: 'var(--vb-border)',
          btn: 'var(--vb-btn)',
          'btn-bd': 'var(--vb-btn-bd)',
          primary: 'var(--vb-primary)',
          'primary-bd': 'var(--vb-primary-bd)',
          'build-bg': 'var(--vb-build-bg)',
          'build-bd': 'var(--vb-build-bd)',
          tint: {
            ok: 'var(--vb-tint-ok-bg)',
            'ok-bd': 'var(--vb-tint-ok-bd)',
            err: 'var(--vb-tint-err-bg)',
            'err-bd': 'var(--vb-tint-err-bd)',
            warn: 'var(--vb-tint-warn-bg)',
            'warn-bd': 'var(--vb-tint-warn-bd)',
            info: 'var(--vb-tint-info-bg)',
            'info-bd': 'var(--vb-tint-info-bd)',
            vibe: 'var(--vb-tint-vibe-bg)',
            'vibe-bd': 'var(--vb-tint-vibe-bd)',
            idle: 'var(--vb-tint-idle-bg)',
            'idle-bd': 'var(--vb-tint-idle-bd)',
          },
          managed: {
            'ok-bg': 'var(--vb-managed-ok-bg)',
            'ok-bd': 'var(--vb-managed-ok-bd)',
            'idle-bg': 'var(--vb-managed-idle-bg)',
            'idle-bd': 'var(--vb-managed-idle-bd)',
          },
          stage: {
            'done-bg': 'var(--vb-stage-done-bg)',
            'done-bd': 'var(--vb-stage-done-bd)',
            'active-bg': 'var(--vb-stage-active-bg)',
            'active-bd': 'var(--vb-stage-active-bd)',
            'failed-bg': 'var(--vb-stage-failed-bg)',
            'failed-bd': 'var(--vb-stage-failed-bd)',
            'held-bg': 'var(--vb-stage-held-bg)',
            'held-bd': 'var(--vb-stage-held-bd)',
            'pending-bd': 'var(--vb-stage-pending-bd)',
          },
        },
      },
      fontSize: {
        'vb-9': ['9.5px', { lineHeight: '1.4', letterSpacing: '0' }],
        'vb-10': ['10px', { lineHeight: '1.4' }],
        'vb-10u': ['10px', { lineHeight: '1.4', letterSpacing: '0.1em' }],
        'vb-105': ['10.5px', { lineHeight: '1.5' }],
        'vb-11': ['11.5px', { lineHeight: '1.45' }],
        'vb-12': ['12px', { lineHeight: '1.58' }],
        'vb-14': ['14px', { lineHeight: '1.35', letterSpacing: '-0.012em' }],
        'vb-145': ['14.5px', { lineHeight: '1.35', letterSpacing: '-0.012em' }],
        'vb-16': ['16px', { lineHeight: '1.2', letterSpacing: '-0.02em' }],
      },
      spacing: {
        'vb-7': '7px',
        'vb-8': '8px',
        'vb-9': '9px',
        'vb-13': '13px',
        'vb-14': '14px',
      },
      borderRadius: {
        vb: '7px',
        'vb-sm': '6px',
        'vb-pill': '4px',
      },
    },
  },
  plugins: [],
};
